name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    
    - name: Create env file
      run: |
        echo "BASE_URL=${{ secrets.BASE_URL }}" > src/utilities/test.env
        echo "API_KEY=${{ secrets.API_KEY }}" >> src/utilities/test.env
        
    - run: npm test
